FROM gradescope/auto-builds:ubuntu-22.04

RUN apt-get update -y
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:plt/racket -y
RUN apt-get install -y racket xvfb
RUN apt-get clean
RUN raco setup --doc-index --force-user-docs
